### ISSUE TITLE
Getting this extension into Open VSX repository

### ISSUE THREAD

**Issue by mclang** [earshinov/vscode-simple-alignment#1]
Hello

I'm using VS Code OSS that doesn't use MS marketplace as default. Instead extensions are installed from [Open VSX](https://open-vsx.org/).

Would it be possible you to put this extension also there?

**Comment by earshinov** [comment]
Hi @mclang, 

I will take a look, probably this week.

**Comment by earshinov** [comment]
@mclang , there you have it: https://open-vsx.org/extension/earshinov/simple-alignment

Currently there is a warning at the top - I'm in the process of having my publisher name approved: https://github.com/EclipseFdn/open-vsx.org/issues/426.

Please let me know how it goes. If everything is okay, I will publish my other extensions there as well.

**Comment by mclang** [comment]
Thanks a lot :pray:

**Comment by earshinov** [comment]
For the record, I published [all of my extensions](https://marketplace.visualstudio.com/publishers/earshinov) to the Open VSX registry as well. You can find them by my username: https://open-vsx.org/?search=earshinov&category=&sortBy=relevance&sortOrder=desc
