### ISSUE TITLE
Documentation doesn't instruct how to select the alignment character.

### ISSUE THREAD

**Issue by zacharysyoung** [earshinov/vscode-simple-alignment#3]
I know the video should be good enough, but I don't understand how to select the alignment chars in the first place.

Will you please explain the selection method? What's that little UI element that pops up just before you choose Alignment?

**Comment by zacharysyoung** [comment]
Okay, just found https://code.visualstudio.com/docs/editor/codebasics for myself and:

> ⌘D selects the word at the cursor, or the next occurrence of the current selection.

 but it'd be helpful to include some description of what's happening in the video to give novices a shot at using this.

**Comment by earshinov** [comment]
Thanks for suggestion! I have included the Basic Editing link you mentioned into the README

**Comment by zacharysyoung** [comment]
Super, thank you :)
